<?php
namespace frontend\controllers;

use Yii;
use yii\helpers\Url;
use yii\web\Controller;
use app\models\GoodsInfo;
use app\models\UserInfo;
use app\models\UserPower;
use app\models\AttrInfo;
use app\models\DemandsInfo;
use app\models\ClassInfo;
use app\models\PushProduct;

/**
 *  商品信息类
 */
class GoodsSendController extends Controller
{
    //关闭CSRF拦截
    public $enableCsrfValidation = false;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * 发送方案页面
     * @return mixed
     */
    public function actionIndex($id)
    {
        //使用会展编辑的布局页面
        $this->layout='@app/views/layouts/demandsMain.php';

        //如果访问的地址没有来源地址跳转到首页
        $callback_url = !empty($_SERVER['REQUEST_URI']) ? Yii::$app->params['website'].$_SERVER['REQUEST_URI'] : Yii::$app->params['website'].Url::to(['solution/index']);
        //问题提示页跳转地址
        $return_url = !empty($_SERVER['HTTP_REFERER']) ? $_SERVER['HTTP_REFERER'] : Yii::$app->params['website'].Url::to(['solution/index']);
        Yii::$app->session->setFlash('return_url',$return_url);

        //判断是否登录
        if (\Yii::$app->user->isGuest) {
            return Yii::$app->getResponse()->redirect( Yii::$app->params['caUrl'] . urlencode($callback_url));
        } else {
            if (isset($_SESSION['phpCAS']['attributes']['user_type'])){
                $user_type = $_SESSION['phpCAS']['attributes']['user_type'];
            } else {
                //判断是否登录
                $user_id = $_SESSION['phpCAS']['attributes']['uid'];
                $user_type = UserPower::get_user_type($user_id);
                $user_type = $_SESSION['phpCAS']['attributes']['user_type'] = $user_type;
            }
        }

        $return_url = Yii::$app->session->getFlash('return_url');
        //如果不是供应商，则跳转到提示页面
        if ($user_type == 3){
            return $this->render('error_notice',['callback_url'=>$return_url]);
        }

        if (!isset($id) || empty($id)){
            echo '参数错误，请重新输入';
            die;
        }

        //解决方案分类id
        $class_id = Yii::$app->params['project_id'];
        //需求数据
        $demands = DemandsInfo::get_info($id);
        $result['demands'] = empty($demands) ? '' : $demands;
        //最新需求列表
        $result['newest_demands'] = DemandsInfo::get_newest_demands($class_id,4,'solution');
        //领域信息
        $domain_attr = AttrInfo::get_class_attr($class_id,'所属领域');
        $result['domains'] = empty($domain_attr['default_value']) ? '' : explode(',',$domain_attr['default_value']);

        return $this->render('index',["data"=>$result]);
    }

    /**
     * 发送科技成果页面
     * @return mixed
     */
    public function actionTech($id)
    {
        //使用会展编辑的布局页面
        $this->layout='@app/views/layouts/techDemandsMain.php';

        //如果访问的地址没有来源地址跳转到首页
        $callback_url = !empty($_SERVER['REQUEST_URI']) ? Yii::$app->params['website'].$_SERVER['REQUEST_URI'] : Yii::$app->params['website'].Url::to(['solution/index']);
        //问题提示页跳转地址
        $return_url = !empty($_SERVER['HTTP_REFERER']) ? $_SERVER['HTTP_REFERER'] : Yii::$app->params['website'].Url::to(['solution/index']);
        Yii::$app->session->setFlash('return_url',$return_url);

        //判断是否登录
        if (\Yii::$app->user->isGuest) {
            return Yii::$app->getResponse()->redirect( Yii::$app->params['caUrl'] . urlencode($callback_url));
        } else {
            if (isset($_SESSION['phpCAS']['attributes']['user_type'])){
                $user_type = $_SESSION['phpCAS']['attributes']['user_type'];
            } else {
                //判断是否登录
                $user_id = $_SESSION['phpCAS']['attributes']['uid'];
                $user_type = UserPower::get_user_type($user_id);
                $user_type = $_SESSION['phpCAS']['attributes']['user_type'] = $user_type;
            }
        }

        $return_url = Yii::$app->session->getFlash('return_url');
        //如果不是供应商，则跳转到提示页面
        if ($user_type == 3){
            return $this->render('error_notice2',['callback_url'=>$return_url]);
        }

        if (!isset($id) || empty($id)){
            echo '参数错误，请重新输入';
            die;
        }
        //科技成果分类id
        $class_id = Yii::$app->params['scientific_id'];
        //需求数据
        $demands = DemandsInfo::get_info($id);
        $result['demands'] = empty($demands) ? '' : $demands;
        //最新需求列表
        $result['newest_demands'] = DemandsInfo::get_newest_demands($class_id,4);
        //领域信息
        $domain_attr = AttrInfo::get_class_attr($class_id,'所属领域');
        //科技成果分类，下拉显示显示用，分类ID固定这个
        $tech_class_id = Yii::$app->params['tech_class_id'];

        //分类信息
        $tech_class = ClassInfo::get_class($tech_class_id);
        $result['classify'] = empty($tech_class) ? array() : $tech_class;

        return $this->render('tech',["data"=>$result]);
    }

    /**
     * 解决方案列表
     */
    public function actionGetProject(){
        $domain = $_GET['domain'];
        $search = $_GET['search'];

        $project_result = GoodsInfo::getProjectByDomain($domain,$search);
        echo self::show_ajax($project_result,200);
    }

    /**
     * 科技成果列表
     */
    public function actionGetTech(){
        $class_id = $_GET['domain'];
        $search = $_GET['search'];

        $project_result = GoodsInfo::getProjectByClass($class_id,$search);
        echo self::show_ajax($project_result,200);
    }

    /**
     * 发送方案或解决成果
     */
    public function actionSendProject(){
        //方案id
        $project_id = $_POST['project_id'];
        //需求id
        $demands_id = $_POST['demands_id'];
        //推送公司id
        $user_id = '';

        //判断是否登录
        if (\Yii::$app->user->isGuest) {
            echo self::show_ajax('',500,'请登录后操作');
            die;
        } else {
            $user_id = $_SESSION['phpCAS']['attributes']['uid'];
        }

        //判断所传参数
        if (empty($project_id) || empty($demands_id) || empty($user_id)){
            echo self::show_ajax('',500,'参数错误，请重新提交');
            die;
        }

        //需求信息
        $data['demands_info'] = DemandsInfo::get_info($demands_id);
        //方案信息
        $data['project_info'] = GoodsInfo::get_info($project_id);
        //用户信息
        $data['user_info'] = UserInfo::get_user($user_id);

        //判断是否是自己推送给自己
        if ($user_id == $data['demands_info']['corp_id']) {
            echo self::show_ajax('',500,'推送错误，您不能推送给自己');
            die;
        }

        $result = PushProduct::create_record($data);
        if ($result){
            echo self::show_ajax('',200);
        } else {
            echo self::show_ajax('',500);
        }
    }

    /**
     * @param string $code 状态码，默认200
     * @param array $data 返回数据
     * @param string $error 信息
     */
    public static function show_ajax($data=array(),$code=200,$info=""){
        if ($code == 200){
            $status = true;
        } else {
            $status = false;
        }

        $array = array(
            'code'=>$code,
            'success'=>$status,
            'data'=>$data,
            'info'=>$info
        );

        return json_encode($array);
    }

    /**
     * 打印格式化后的变量
     * @param $param
     * @param bool $type
     */
    public static function P($param,$type=false){
        echo '<pre>';
        if($type){
            var_export($param);
        } else {
            print_r($param);
        }
        echo '</pre>';
    }
}
